# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-30 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='torrentdownload',
            name='peers',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
